# Generated by Django 4.0.5 on 2022-06-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0002_mypages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=100)),
                ('what', models.CharField(max_length=100)),
                ('posifaction', models.CharField(max_length=100)),
                ('negafaction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('sub_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Natures',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=180)),
                ('demeanor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoguishFeats',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charm', models.SmallIntegerField()),
                ('cunning', models.SmallIntegerField()),
                ('finesse', models.SmallIntegerField()),
                ('luck', models.SmallIntegerField()),
                ('might', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSkills',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MyPages',
        ),
        migrations.AlterField(
            model_name='drives',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
